# Generated by Django 2.0.3 on 2019-11-26 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100)),
                ('proprietor_name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('mobile', models.CharField(blank=True, max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('staring_year', models.IntegerField()),
                ('address', models.TextField(blank=True, max_length=500)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_name', models.CharField(max_length=150)),
                ('proprietor_name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('mobile1', models.CharField(blank=True, max_length=50)),
                ('mobile2', models.CharField(blank=True, max_length=50)),
                ('staring_year', models.IntegerField()),
                ('address', models.TextField(blank=True, max_length=500)),
                ('status', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.Branches')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Company Information',
            },
        ),
        migrations.CreateModel(
            name='CustomerRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=80)),
                ('mobile', models.CharField(max_length=16)),
                ('mobile2', models.CharField(blank=True, max_length=16)),
                ('nid_number', models.CharField(max_length=50)),
                ('customer_image', models.ImageField(blank=True, upload_to='customer_image/')),
                ('nid_image', models.ImageField(blank=True, upload_to='nid_image/')),
                ('present_address', models.TextField(blank=True)),
                ('permanent_address', models.TextField(blank=True)),
                ('profession', models.CharField(blank=True, max_length=150)),
                ('reference_person', models.CharField(blank=True, max_length=50)),
                ('reference_address', models.CharField(blank=True, max_length=150)),
                ('reference_mobile', models.CharField(blank=True, max_length=15)),
                ('reg_date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.Branches')),
            ],
            options={
                'verbose_name': 'Customer Registration',
                'verbose_name_plural': 'Customer Registrations',
            },
        ),
        migrations.CreateModel(
            name='InstallmentCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.FloatField(default=0)),
                ('due_date', models.DateTimeField()),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.Branches')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.CustomerRegistration')),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Installment Collections',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('brand_name', models.CharField(blank=True, max_length=150)),
                ('product_image', models.ImageField(blank=True, upload_to='product_image/')),
                ('product_model_number', models.CharField(blank=True, max_length=100)),
                ('product_color', models.CharField(blank=True, max_length=50)),
                ('available_quantity', models.IntegerField(default=1)),
                ('total_quantity', models.IntegerField(default=1)),
                ('unit_price_by_cash', models.FloatField(default=0)),
                ('unit_price_by_installment', models.FloatField(default=0)),
                ('total_price', models.FloatField(default=0)),
                ('buy_price', models.FloatField(default=0)),
                ('maximum_discount', models.FloatField(blank=True, default=0)),
                ('discription', models.TextField(blank=True)),
                ('status', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.Branches')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.Branches')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='SaleProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('1', 'Full Payment'), ('2', 'Installment')], max_length=1)),
                ('sale_quantity', models.IntegerField(default=1)),
                ('discount', models.FloatField(default=0)),
                ('total_price', models.FloatField(default=0)),
                ('due_amount', models.FloatField(default=0)),
                ('comment', models.TextField(blank=True)),
                ('next_installment_date', models.DateTimeField()),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.Branches')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.CustomerRegistration')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.Product')),
            ],
            options={
                'verbose_name': 'Sales Product',
                'verbose_name_plural': 'Sales Products',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.ProductCat'),
        ),
        migrations.AddField(
            model_name='installmentcollection',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.SaleProducts'),
        ),
    ]
