# Generated by Django 2.0.3 on 2019-11-25 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashSalesProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_quantity', models.IntegerField(default=1)),
                ('discount', models.FloatField(default=0)),
                ('total_price', models.FloatField(default=0)),
                ('comment', models.TextField(blank=True)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sales Product',
                'verbose_name_plural': 'Sales Products',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_name', models.CharField(max_length=150)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('mobile1', models.CharField(blank=True, max_length=50)),
                ('mobile2', models.CharField(blank=True, max_length=50)),
                ('staring_year', models.IntegerField()),
                ('address', models.TextField(blank=True, max_length=500)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Company Information',
            },
        ),
        migrations.CreateModel(
            name='CustomerRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=80)),
                ('mobile1', models.CharField(blank=True, max_length=16)),
                ('mobile2', models.CharField(blank=True, max_length=16)),
                ('home_phone', models.CharField(blank=True, max_length=16)),
                ('nid_number', models.CharField(max_length=50)),
                ('nid_image', models.ImageField(blank=True, upload_to='nid_image/')),
                ('present_address', models.TextField(blank=True)),
                ('permanent_address', models.TextField(blank=True)),
                ('profession', models.CharField(blank=True, max_length=150)),
                ('reg_date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Customer Registration',
                'verbose_name_plural': 'Customer Registrations',
            },
        ),
        migrations.CreateModel(
            name='InstallmentSalesProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_quantity', models.IntegerField(default=1)),
                ('cash_payment', models.FloatField(default=0)),
                ('installment_amount_month', models.FloatField(default=0)),
                ('installment_paid_date', models.DateTimeField()),
                ('total_price', models.FloatField(default=0)),
                ('contact_number', models.CharField(blank=True, max_length=16)),
                ('comment', models.TextField(blank=True)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.CustomerRegistration')),
            ],
            options={
                'verbose_name': 'Sales Product',
                'verbose_name_plural': 'Sales Products',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('brand_name', models.CharField(blank=True, max_length=150)),
                ('product_image', models.ImageField(blank=True, upload_to='product_image/')),
                ('product_model_number', models.CharField(blank=True, max_length=100)),
                ('product_color', models.CharField(blank=True, max_length=50)),
                ('available_quantity', models.IntegerField(default=1)),
                ('total_quantity', models.IntegerField(default=1)),
                ('unit_price_by_cash', models.FloatField(default=0)),
                ('unit_price_by_installment', models.FloatField(default=0)),
                ('total_price', models.FloatField(default=0)),
                ('buy_price', models.FloatField(default=0)),
                ('maximum_discount', models.FloatField(blank=True, default=0)),
                ('discription', models.TextField(blank=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.ProductCat'),
        ),
        migrations.AddField(
            model_name='installmentsalesproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.Product'),
        ),
        migrations.AddField(
            model_name='cashsalesproduct',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.CustomerRegistration'),
        ),
        migrations.AddField(
            model_name='cashsalesproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.Product'),
        ),
    ]
