# Generated by Django 2.0.3 on 2019-11-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0002_branches_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerregistration',
            old_name='mobile2',
            new_name='mobile1',
        ),
        migrations.AlterField(
            model_name='customerregistration',
            name='reference_address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='customerregistration',
            name='reference_person',
            field=models.CharField(max_length=50),
        ),
    ]
