# Generated by Django 2.0.3 on 2019-11-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0003_auto_20191128_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleproducts',
            name='per_installment_amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='saleproducts',
            name='sale_unit_price',
            field=models.IntegerField(default=1),
        ),
    ]
