# Generated by Django 2.0.3 on 2019-11-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0006_auto_20191128_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleproducts',
            name='sale_date',
            field=models.DateField(),
        ),
    ]
