# Generated by Django 2.0.3 on 2019-11-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0009_customerregistration_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentcollection',
            name='payment_date',
            field=models.DateTimeField(),
        ),
    ]
