# Generated by Django 2.0.3 on 2019-11-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0011_content_domain_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='branch_logo',
            field=models.ImageField(blank=True, upload_to='branch_logo/'),
        ),
        migrations.AddField(
            model_name='content',
            name='company_logo',
            field=models.ImageField(blank=True, upload_to='company_logo/'),
        ),
    ]
